import { beforeEach, describe, expect, it, vi } from "vitest";

import type { RtgTrail } from "@/lib/types";

const mockGetRtgTrails = vi.fn<() => Promise<RtgTrail[]>>();
const mockFetchOsmHikingTrails = vi.fn<() => Promise<RtgTrail[]>>();
const mockPlanRoute = vi.fn();

vi.mock("@/lib/api/rtg-client", () => ({
  getRtgTrails: () => mockGetRtgTrails(),
}));

vi.mock("@/lib/api/osm-trails-client", () => ({
  fetchOsmHikingTrails: () => mockFetchOsmHikingTrails(),
}));

vi.mock("@/lib/optimization/route-planner", () => ({
  planRoute: (...args: unknown[]) => mockPlanRoute(...args),
}));

import { searchBestHike } from "@/lib/optimization/hike-search";

describe("searchBestHike", () => {
  beforeEach(() => {
    mockFetchOsmHikingTrails.mockResolvedValue([]);
  });
  it("labels RTG results as ORS-generated guidance instead of official trail geometry", async () => {
    mockGetRtgTrails.mockResolvedValueOnce([
      {
        id: "candidate-1",
        name: "Candidate",
        region: "Jerusalem",
        lengthMeters: 3500,
        difficulty: "easy",
        source: "rtg-curated",
        dataVersion: "2026-04-03",
        lastUpdated: "2026-04-03T00:00:00.000Z",
        geometry: [
          { lat: 31.7683, lng: 35.2137 },
          { lat: 31.769, lng: 35.215 },
          { lat: 31.77, lng: 35.216 },
        ],
      },
    ]);

    mockPlanRoute.mockResolvedValueOnce({
      orderedWaypoints: [],
      segments: [],
      geometry: [
        { lat: 31.7683, lng: 35.2137 },
        { lat: 31.769, lng: 35.2145 },
      ],
      totalDistanceMeters: 2800,
      totalDurationSeconds: 2400,
      warnings: [],
    });

    const result = await searchBestHike({
      origin: { lat: 31.7683, lng: 35.2137 },
    });

    expect(result.route.source).toBe("rtg");
    expect(result.selected.routeApproximated).toBe(true);
    expect(result.route.sourceLabel).toBe(
      "RTG-Guided Route (curated trail, path approximated)",
    );
    expect(result.route.warnings).toContain(
      "Route path is generated by ORS from a curated RTG-style trail dataset and may not exactly follow the official marked trail.",
    );
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("Applied automatic start-distance filter"),
      ),
    ).toBe(true);
  });

  it("respects desiredRouteCount for alternates", async () => {
    mockGetRtgTrails.mockResolvedValueOnce([
      {
        id: "candidate-1",
        name: "Candidate 1",
        region: "Jerusalem",
        lengthMeters: 3500,
        source: "rtg-curated",
        dataVersion: "2026-04-03",
        lastUpdated: "2026-04-03T00:00:00.000Z",
        geometry: [
          { lat: 31.7683, lng: 35.2137 },
          { lat: 31.769, lng: 35.215 },
          { lat: 31.77, lng: 35.216 },
        ],
      },
      {
        id: "candidate-2",
        name: "Candidate 2",
        region: "Jerusalem",
        lengthMeters: 3600,
        source: "rtg-curated",
        dataVersion: "2026-04-03",
        lastUpdated: "2026-04-03T00:00:00.000Z",
        geometry: [
          { lat: 31.7684, lng: 35.2138 },
          { lat: 31.7691, lng: 35.2151 },
          { lat: 31.7701, lng: 35.2161 },
        ],
      },
      {
        id: "candidate-3",
        name: "Candidate 3",
        region: "Jerusalem",
        lengthMeters: 3700,
        source: "rtg-curated",
        dataVersion: "2026-04-03",
        lastUpdated: "2026-04-03T00:00:00.000Z",
        geometry: [
          { lat: 31.7685, lng: 35.2139 },
          { lat: 31.7692, lng: 35.2152 },
          { lat: 31.7702, lng: 35.2162 },
        ],
      },
    ]);

    mockPlanRoute.mockResolvedValueOnce({
      orderedWaypoints: [],
      segments: [],
      geometry: [{ lat: 31.7683, lng: 35.2137 }],
      totalDistanceMeters: 2800,
      totalDurationSeconds: 2400,
      warnings: [],
    });

    const result = await searchBestHike({
      origin: { lat: 31.7683, lng: 35.2137 },
      preferences: { desiredRouteCount: 3 },
    });

    expect(result.alternates).toHaveLength(2);
    expect(
      result.route.warnings.some((warning) => warning.includes("Nearby alternatives:")),
    ).toBe(true);
  });

  it("falls back when all RTG candidates are unusable", async () => {
    mockGetRtgTrails.mockResolvedValueOnce([
      {
        id: "candidate-1",
        name: "Candidate",
        region: "Jerusalem",
        lengthMeters: 3500,
        difficulty: "easy",
        source: "rtg-curated",
        dataVersion: "2026-04-03",
        lastUpdated: "2026-04-03T00:00:00.000Z",
        geometry: [
          { lat: 31.7683, lng: 35.2137 },
          { lat: 31.769, lng: 35.215 },
          { lat: 31.77, lng: 35.216 },
        ],
      },
    ]);

    let callCount = 0;
    mockPlanRoute.mockImplementation(() => {
      callCount += 1;
      if (callCount === 1) {
        throw new Error("Failed route from RTG candidate");
      }
      return {
        orderedWaypoints: [],
        segments: [],
        geometry: [],
        totalDistanceMeters: 1000,
        totalDurationSeconds: 900,
        warnings: [],
      };
    });

    const result = await searchBestHike({
      origin: { lat: 31.7683, lng: 35.2137 },
    });

    expect(result.selected.source).toBe("fallback");
    expect(result.route.source).toBe("fallback");
    expect(result.fallbackReason).toContain("malformed or unusable");
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("final responsibility remains with you"),
      ),
    ).toBe(true);
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("Try increasing the max distance constraint"),
      ),
    ).toBe(false);
  });

  it("adds fallback guidance and constraint hints when no RTG candidate matches", async () => {
    mockGetRtgTrails.mockResolvedValueOnce([]);
    mockPlanRoute.mockResolvedValueOnce({
      orderedWaypoints: [],
      segments: [],
      geometry: [],
      totalDistanceMeters: 1200,
      totalDurationSeconds: 1000,
      warnings: [],
    });

    const result = await searchBestHike({
      origin: { lat: 31.7683, lng: 35.2137 },
      endpoint: { lat: 31.78, lng: 35.25 },
      preferences: { maxDistanceMeters: 2000 },
      targetDistanceMeters: 2500,
    });

    expect(result.route.source).toBe("fallback");
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("No official RTG trail was found"),
      ),
    ).toBe(true);
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("Try increasing the max distance constraint"),
      ),
    ).toBe(true);
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("Try removing the endpoint constraint temporarily"),
      ),
    ).toBe(true);
    expect(
      result.route.warnings.some((warning) =>
        warning.includes("relaxing the target finish distance"),
      ),
    ).toBe(true);
  });
});
