import { describe, expect, it } from "vitest";

import { buildTrailIntelligenceReport } from "@/lib/trail-intelligence/build-briefing";
import type { CalculatedRoute } from "@/lib/types";

const baseRoute: CalculatedRoute = {
  orderedWaypoints: [
    {
      id: "w1",
      name: "Start",
      coordinates: { lat: 31.7683, lng: 35.2137 },
      required: true,
      isStart: true,
      isEnd: false,
    },
    {
      id: "w2",
      name: "Finish",
      coordinates: { lat: 31.779, lng: 35.22 },
      required: true,
      isStart: false,
      isEnd: true,
    },
  ],
  segments: [
    {
      from: {
        id: "w1",
        name: "Start",
        coordinates: { lat: 31.7683, lng: 35.2137 },
        required: true,
        isStart: true,
        isEnd: false,
      },
      to: {
        id: "w2",
        name: "Finish",
        coordinates: { lat: 31.779, lng: 35.22 },
        required: true,
        isStart: false,
        isEnd: true,
      },
      distanceMeters: 5400,
      durationSeconds: 4500,
      geometry: [
        { lat: 31.7683, lng: 35.2137 },
        { lat: 31.779, lng: 35.22 },
      ],
      steps: [],
    },
  ],
  geometry: [
    { lat: 31.7683, lng: 35.2137 },
    { lat: 31.779, lng: 35.22 },
  ],
  totalDistanceMeters: 5400,
  totalDurationSeconds: 4500,
  warnings: [],
  source: "rtg",
  sourceLabel: "RTG-guided route (path generated by ORS)",
};

describe("buildTrailIntelligenceReport", () => {
  it("returns a structured heuristic briefing with source coverage notes", () => {
    const report = buildTrailIntelligenceReport({
      route: baseRoute,
      generatedAt: "2026-08-03T11:30:00.000Z",
    });

    expect(report.regionLabel).toBe("Jerusalem hills");
    expect(report.recommendation.level).toBe("caution");
    expect(report.routeSummary.summary).toContain("RTG-guided route");
    expect(report.currentConditions.sourceStatus).toBe("heuristic");
    expect(report.sourceNotes).toHaveLength(3);
  });

  it("downgrades safety when routing warnings exist", () => {
    const report = buildTrailIntelligenceReport({
      route: {
        ...baseRoute,
        source: "fallback",
        warnings: ["Manual verification required"],
      },
      generatedAt: "2026-04-03T07:30:00.000Z",
    });

    expect(report.safety.level).toBe("caution");
    expect(report.recommendation.reasons.some((reason) => reason.includes("warnings"))).toBe(
      true,
    );
  });
});
